name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with: 
        node-version: 12.x
    
    # Instalar as dependências Yarn
    - name: Install dependencies
      run: yarn
      
    # Executar build
    - name: Run build
      run: yarn build
      
    # Copiar código novo para dentro da Digital Ocean
    - name: Copy code to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: ".,!node_modules"
        target: "~/app/gostack-gobarber-backend"

    # Executar o Yarn na Digital Ocean
    # Executar as migrations do TypeORM
    # Restart no servidor Node.js
    - name: Run production scripts on Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/app/gostack-gobarber-backend
          yarn
          ./node_modules/.bin/typeorm migration:run
          pm2 restart gobarber-api
