name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with: 
        node-version: 12.x
    
    # Instalar as dependências Yarn
    - name: Install dependencies
      run: yarn
      
    # Executar build
    - name: Run build
      run: yarn build
      
    # Copiar pasta dist para dentro da Digital Ocean
    - name: Copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "dist"
        target: "test"

    # Substituir o código antigo pelo novo código
    # Executar o Yarn na Digital Ocean
    # Executar as migrations do TypeORM
    # Restart no servidor Node.js
